# -*- coding: utf-8 -*-
"""NoisePollution_USA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gdtXx1IcOx4JtHSTNyPX_iJszJcDFrRh

Name: Vaishnavi Shirsekar.

Course: IGME-770 Spatial Data Science
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# Optional: For interactive visualizations
import plotly.express as px

# Load the dataset from the specified path
file_path = '/content/us_congestion_2016_2022_sample_2m.csv'
df = pd.read_csv(file_path)

# Display the first few rows of the dataset
df.head()

# Check for missing values
print(df.isnull().sum())

# Fill missing values or drop them (depending on your strategy)
df.fillna(method='ffill', inplace=True)  # Example: forward-fill method

# Check for duplicates and drop if necessary
df.drop_duplicates(inplace=True)

# Convert any categorical variables to numerical, if necessary
# Example: convert region or category columns to numerical codes if needed
# df['region'] = df['region'].astype('category').cat.codes

# Group data by 'State' and calculate the mean for 'Severity'
state_severity = df.groupby('State')['Severity'].mean().reset_index()

# Sort the data for better visualization
state_severity = state_severity.sort_values(by='Severity', ascending=False)

plt.figure(figsize=(9, 8))
sns.barplot(data=state_severity, x='Severity', y='State')
plt.title('Average Noise Severity by State (2016–2022)')
plt.xlabel('Severity (Noise Level)')
plt.ylabel('State')
plt.show()

import plotly.express as px

# Plot interactive visualization for Noise Severity by State
fig = px.bar(state_severity, x='Severity', y='State', orientation='h',
             title='Noise Severity by State (2016-2022)',
             labels={'Severity': 'Noise Level', 'State': 'State'})
fig.show()

plt.figure(figsize=(12, 8))
heatmap_data = pd.pivot_table(df, values='Severity', index='State', aggfunc=np.mean)
sns.heatmap(heatmap_data, cmap='coolwarm', annot=True)
plt.title('Heatmap of Noise Severity by State (2016-2022)')
plt.xlabel('State')
plt.show()

# First, convert 'StartTime' to a datetime object, handling timezone-aware data properly
df['StartTime'] = pd.to_datetime(df['StartTime'], errors='coerce', utc=True)

# Remove the timezone information by converting to naive datetime
df['StartTime'] = df['StartTime'].dt.tz_localize(None)

# Now filter the dataset for the year 2020
df_2020 = df[df['StartTime'].dt.year == 2020]

# Group data by 'State' and calculate the mean severity for 2020
state_severity_2020 = df_2020.groupby('State')['Severity'].mean().reset_index()

# Sort the data for better visualization
state_severity_2020 = state_severity_2020.sort_values(by='Severity', ascending=False)

plt.figure(figsize=(9, 8))  # Adjusted figure size to 9x8

# No need for palette or hue when there are no categorical variables
sns.barplot(data=state_severity_2020, x='Severity', y='State')

plt.title('Average Noise Severity by State for 2020')
plt.xlabel('Severity (Noise Level)')
plt.ylabel('State')
plt.show()

# Find the state with the highest average noise (Severity) for 2020
highest_noise_state = state_severity_2020.loc[state_severity_2020['Severity'].idxmax()]

# Print the state with the highest noise level
print(f"The state with the highest average noise level in 2020 is {highest_noise_state['State']} with a severity level of {highest_noise_state['Severity']:.2f}")

import plotly.express as px

# Create a choropleth map with the desired color scale (Red for highest, Green for lowest)
fig = px.choropleth(state_severity_2020,
                    locations='State',
                    locationmode='USA-states',  # Use state-level mapping
                    color='Severity',
                    color_continuous_scale='RdYlGn_r',  # Red-to-Green scale, reversed to have red as highest
                    scope='usa',
                    labels={'Severity':'Noise Level'},
                    title='Average Noise Severity by State for 2020')

# Display the map
fig.show()

import plotly.express as px

# Define a custom color scale that goes from black (low) to red (high)
custom_color_scale = [
    [0.0, 'black'],   # Lowest value
    [1.0, 'red']      # Highest value
]

# Create the choropleth map with the custom black-to-red color scale
fig = px.choropleth(state_severity_2020,
                    locations='State',
                    locationmode='USA-states',  # Use state-level mapping
                    color='Severity',
                    color_continuous_scale=custom_color_scale,  # Apply custom color scale
                    scope='usa',
                    labels={'Severity':'Noise Level'},
                    title='Average Noise Severity by State for 2020')

# Update layout to adjust the figure size (9x8 inches)
fig.update_layout(
    width=900,  # 9 inches = 900 px
    height=800  # 8 inches = 800 px
)

# Display the map
fig.show()

import plotly.express as px

# Bubble chart with state names
fig = px.scatter(state_severity_2020,
                 x='State',
                 y='Severity',
                 size='Severity',
                 color='Severity',
                 color_continuous_scale='RdYlGn_r',
                 title='Noise Severity by State for 2020',
                 labels={'Severity':'Noise Level', 'State':'State'})
fig.show()

plt.figure(figsize=(9, 8))
sns.boxplot(data=state_severity_2022, x='Severity', palette='RdYlGn_r')
plt.title('Distribution of Noise Severity Across States for 2020')
plt.xlabel('Noise Severity')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Sort by severity for better visualization
state_severity_2020_sorted = state_severity_2020.sort_values(by='Severity', ascending=False)

# Create a heatmap
plt.figure(figsize=(9, 8))
sns.heatmap(state_severity_2020_sorted.set_index('State')['Severity'].to_frame().T,
            cmap='RdYlGn_r', cbar=True, annot=True)
plt.title('Heatmap of Average Noise Severity by State for 2022')
plt.xlabel('State')
plt.ylabel('Noise Severity')
plt.xticks(rotation=45, ha='right')
plt.show()